### ISSUE TITLE
Addon not working since last nightly

### ISSUE THREAD

**Issue by moimael** [fabricedesre/b2gremote#1]
Hi,

I just updated my nightly release of firefox (21a1) and now I can't use this addon anymore. It does not connect to the device and you cannot choose a file.

I talked with other dev and i'm not the only one having this issue.

Since it is the more convenient way of testing privileged packaged apps, I hope it will be fixed soon.

 Thanks !

**Comment by nickdesaulniers** [comment]
Please pull the latest changes and verify.
